### ISSUE TITLE
Failed to mount component: template or render function not defined

### ISSUE THREAD

**Issue by mydnic** [matfish2/vue-stripe#18]
Hello

I'm trying to use this package with Laravel Mix. Importing the package works fine, but when I'm loading the page, I get this error :

```
app.bfe0030….js:33937 [Vue warn]: Failed to mount component: template or render function not defined. 
(found in <StripeCheckout>)
```

Can you help me ?

Thanks a lot

**Comment by albertleao** [comment]
+1 same issue.

Initially I got the following error :

`[Vue warn]: Unknown custom element: <stripe-checkout> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

but then I changed

`import  { StripeCheckout } from 'vue-stripe'`

to 

`import StripeCheckout from 'vue-stripe'`

and now I receive the same error you have above.

**Comment by fornve** [comment]
+1 And here
![screenshot_2017-07-01_18-49-54](https://user-images.githubusercontent.com/85847/27763944-178378a8-5e8e-11e7-87d1-4edffe9230ef.png)


"vue-stripe": "^0.1.3",
"vue": "2.3.3",
node: v6.11.0
npm: 3.10.10

**Comment by messerli90** [comment]
+1 here

vue-stripe: 0.1.3
vue: 2.3.4
node: v6.10.3
npm: 4.2.0

**Comment by flyrmyr** [comment]
+1 same issue.

Webpack shows this warning:
`export 'StripeCheckout' was not found in 'vue-stripe'`
using:
`import { StripeCheckout } from 'vue-stripe'`
but no error shown with:
`import StripeCheckout from 'vue-stripe'`

But in the second, I'm getting a browser error:
`Uncaught ReferenceError: StripeCheckout is not defined`
