### ISSUE TITLE
Custom classes

### ISSUE THREAD

**Issue by mydnic** [matfish2/vue-stripe#25]
Hello !
It would be cool to be able to set our own css classes on the button.
I'm using Bulma so the bootstrap btn classes do not work :(

What do you think ?
Thx!

**Comment by kikky7** [comment]
@matfish2 
Can't you just add to props:
`buttonClass: {
                type: String,
                require: false,
                default: 'btn btn-primary'
            },`

and change this code:
`<button @click.prevent="purchase()"
                class="{{ buttonClass }} btn-stripe-checkout"
                :disabled="!loaded">
            {{ button }}
        </button>`

I tried to do it locally, but no luck, I can't find the way to apply changes on npm package's source files.
