### ISSUE TITLE
Bitcoin Support?

### ISSUE THREAD

**Issue by ghost** [matfish2/vue-stripe#26]
I know Stripe released Bitcoin support for checkout, could this be updated to provide the option of paying with bitcoin?

**Comment by itsmill3rtime** [comment]
@rucuriousyet i ran into the same thing. did some digging through stripe docs and then the source code of this component. 

my solution:
`:options="checkoutOptions"` on the component

then inside the data on your parent component put 
```
checkoutOptions: {
         bitcoin: true,
         amount: 10000
}
```
