### ISSUE TITLE
Question on product

### ISSUE THREAD

**Issue by justin-nodeboy** [matfish2/vue-stripe#29]
Hey 

Quick question, how could I determine which product has been selected? I don't want the form to be submitted so am instead relying on the bus subscribe, but I have 2 payment buttons, both with a different product pre filled in.

I just can't quite figure out how I know which one has been selected?

Any help would be appreciated.

Cheers

**Comment by justin-nodeboy** [comment]
#30 

Added a PR for the option

**Comment by matfish2** [comment]
Merged. Thanks
