### ISSUE TITLE
Question payment methods

### ISSUE THREAD

**Issue by maximaexchen** [matfish2/vue-stripe#31]
Hi.
Is it possible to add multiple payment methods like (SEPA - Europe, and other) beside normal credit card payment possibility on checkout?
I saw the checkout popup on laracast which has to tabs to decide between two methods?
I couldn't find any hint on the net.
Any hint appreciated.
Regards

**Comment by matfish2** [comment]
This plugin is simply a wrapper around the stripe checkout plugin. Please inquire there.

**Comment by maximaexchen** [comment]
Ok thanks anyway
