### ISSUE TITLE
Where to set up the product objet

### ISSUE THREAD

**Issue by catlabs** [matfish2/vue-stripe#6]
Hi,

I m brand new to both stripe and vuejs so my question might be very basic but I don't understand where am I supposed to set up the product json object, neither the options.

I have generated the basic js of laravel 5.3 and I thought I should specify this like so:

```
import { StripeCheckout } from 'vue-stripe';

Vue.component('stripe-checkout', StripeCheckout);

const app = new Vue({
    el: '#app',
    data: {
    	product: {
		    name: 'Moby Dick',
		    description: 'I love whales',
		    amount: 100000 // 100$ in cents
		},
		options: {
			zipCode:true
		}
	}
});

```
Can you tell me what I m doing wrong?

Thanks in advance!

**Comment by matfish2** [comment]
Did you set the view layer? You need to declare the component in your HTML:

```js
<stripe-checkout stripe-key="your-stripe-key" :product="product" :options="options"></stripe-checkout>
```

**Comment by catlabs** [comment]
Allright it works with :product instead of product.

Thanks!
