### ISSUE TITLE
Multiple pay buttons

### ISSUE THREAD

**Issue by catlabs** [matfish2/vue-stripe#8]
Hi,

I need to add multiple pay button on the same page but I realized than the stripe.js script is only added to the first button multiple time actually. I guess you could fix it quite easily if you change the injectCheckoutScript() function.

**Comment by matfish2** [comment]
The script is loaded only once as it should. You don't need multiple scripts for multiple buttons.

**Comment by catlabs** [comment]
Well I think if I have 2 buttons, the injectCheckoutScript() is called 2 times, at the end I got 2 times the script loaded (see screenshot). 

(https://cloud.githubusercontent.com/assets/2089097/21763661/46a91a64-d65f-11e6-8b74-a5390c01bf0e.png)

**Comment by matfish2** [comment]
Did you download the most recent release? The multiple buttons support was added very recently.

**Comment by catlabs** [comment]
Right, did an update and it's working now :-)

Thanks for the great job!
